blank_issues_enabled: true
contact_links:
  - name: LibreNMS API Documentation
    url: https://docs.librenms.org/API/
    about: Official LibreNMS API reference
  - name: LibreNMS Community
    url: https://community.librenms.org/
    about: LibreNMS community forums for general LibreNMS questions

